"""Initial tables

Revision ID: 107215fef3ce
Revises: 
Create Date: 2025-06-20 11:58:40.829356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107215fef3ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tickets_assignee_id_users', 'tickets', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tickets_assignee_id_users', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'assignee_id')
    # ### end Alembic commands ###
