"""add_team_permissions_and_file_support

Revision ID: 29752fc1b287
Revises: 8653a3fe8c8d
Create Date: 2025-06-21 12:12:41.408720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '29752fc1b287'
down_revision: Union[str, None] = '8653a3fe8c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('allow_file_sharing', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('allow_media', sa.Boolean(), nullable=True))
    op.add_column('team_members', sa.Column('can_add_members', sa.Boolean(), nullable=True))
    op.add_column('team_members', sa.Column('can_create_channels', sa.Boolean(), nullable=True))
    op.add_column('team_members', sa.Column('can_share_files', sa.Boolean(), nullable=True))
    op.add_column('team_members', sa.Column('can_delete_messages', sa.Boolean(), nullable=True))
    op.add_column('team_messages', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('team_messages', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('team_messages', sa.Column('file_type', sa.String(length=100), nullable=True))
    op.add_column('team_messages', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('team_messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('team_messages', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('team_messages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('team_messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('team_messages', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.alter_column('team_messages', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('team_messages', 'file_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_foreign_key(None, 'team_messages', 'users', ['deleted_by'], ['id'])
    op.add_column('teams', sa.Column('allow_members_add', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('allow_members_create_channels', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('allow_file_sharing', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('max_file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'max_file_size')
    op.drop_column('teams', 'allow_file_sharing')
    op.drop_column('teams', 'allow_members_create_channels')
    op.drop_column('teams', 'allow_members_add')
    op.drop_constraint(None, 'team_messages', type_='foreignkey')
    op.alter_column('team_messages', 'file_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('team_messages', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.drop_column('team_messages', 'deleted_by')
    op.drop_column('team_messages', 'deleted_at')
    op.drop_column('team_messages', 'is_deleted')
    op.drop_column('team_messages', 'edited_at')
    op.drop_column('team_messages', 'is_edited')
    op.drop_column('team_messages', 'thumbnail_url')
    op.drop_column('team_messages', 'file_type')
    op.drop_column('team_messages', 'file_size')
    op.drop_column('team_messages', 'file_name')
    op.drop_column('team_members', 'can_delete_messages')
    op.drop_column('team_members', 'can_share_files')
    op.drop_column('team_members', 'can_create_channels')
    op.drop_column('team_members', 'can_add_members')
    op.drop_column('channels', 'allow_media')
    op.drop_column('channels', 'allow_file_sharing')
    # ### end Alembic commands ###
